@startuml
scale 550 width

[*] -> Active

Active -up-> Paused
Paused -down-> Active
Active -down-> Refund

Active -> Success
Success -up-> Paused
Paused -down-> Success

Success -> Withdraw

Withdraw -> Paused
Paused -> Withdraw

Refund -> Paused
Paused -> Refund

Paused -> Stopped

Stopped -> [*]

@enduml